services:
  - type: web
    name: lumenquest
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn taskmanager.wsgi:application
    envVars:
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'your-app-name.onrender.com'
